name: build
on: [push]

permissions:
  contents: write

env:
  MINECRAFT_VERSION: 1.20.4
  JAVA_VERSION: 17
  VERSION: 1.0.0+1.20.4
  RELEASE_NAME: PotatoesPlus

jobs:
  build:
    strategy:
      matrix:
        java: [
          17
        ]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
      - name: mc-publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          github-token: ${{ secrets.TOKEN }}
          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
